Use flock in blocking mode.

diff --git a/rp b/rp
--- a/rp
+++ b/rp
@@ -90,8 +90,8 @@ elif [ "$1" != '--runasdaemon' ]; then #Run remote command
     check_daemon
 
     (
-        if ! flock -n 9; then
-            echo "flock of $PROJPIDFILE failed" >&2
+        if ! flock -o 9; then
+            echo "flock of $PROJPIDFILE for command failed: $?" >&2
             exit 60
         fi
         LPWD="$(pwd)"
@@ -129,8 +129,8 @@ coproc inotifywait -q -r -m --format "%w%f" $EVENTS .
 
 #Initial sync
 (
-    if ! flock -n 9; then
-            echo "flock of $PROJPIDFILE failed" >&2
+    if ! flock 9; then
+            echo "flock of $PROJPIDFILE failed: $?" >&2
             exit 78
     fi
 
@@ -155,8 +155,8 @@ while true; do
         exit #timeout/EOF
     fi
     (
-        if ! flock -n 9; then
-            echo "flock of $PROJPIDFILE failed for incremental" >&2
+        if ! flock 9; then
+            echo "flock of $PROJPIDFILE failed for incremental: $?" >&2
             exit 77
         fi
 
